<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_TCMotor" Id="{541e675d-c901-46ef-8343-e944626c84c3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TCMotor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fb_TC_Ap							: DFB_Cylinder;
	_Col_PCWValve_Perm					: WORD;
	_Col_PCWValve_SD									: WORD;
	
	_DUT_TC_e						: DUT_Cylinder;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Action Name="PermSD" Id="{5e1c502e-582d-4762-86b5-bbeb6cc40854}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="FB_TCMotor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TCMotor.PermSD">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>